# なんかしようとしたけど使ってない→結局使った
# mysqlclient をいれる用のやつ
FROM jupyter/datascience-notebook

USER root

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && \
    apt-get -y install gcc libmariadb-dev

USER jovyan
WORKDIR /home/jovyan

RUN pip install mysqlclient